packages:
  - runtime/*
  - portal/*
  - portal-app/*
  - internal-sdk
  - packages/sdk
  - packages/solid-store
  - workspace/
  - workspace-cluster/
  - workspace-desktop/
  - apps/*
  - website
  - cortex
