import hljs from "highlight.js/lib/core";

import g1c from "highlight.js/lib/languages/1c";
import gAbnf from "highlight.js/lib/languages/abnf";
import gAccesslog from "highlight.js/lib/languages/accesslog";
import gActionscript from "highlight.js/lib/languages/actionscript";
import gAda from "highlight.js/lib/languages/ada";
import gAngelscript from "highlight.js/lib/languages/angelscript";
import gApache from "highlight.js/lib/languages/apache";
import gApplescript from "highlight.js/lib/languages/applescript";
import gArcade from "highlight.js/lib/languages/arcade";
import gArduino from "highlight.js/lib/languages/arduino";
import gArmasm from "highlight.js/lib/languages/armasm";
import gXml from "highlight.js/lib/languages/xml";
import gAsciidoc from "highlight.js/lib/languages/asciidoc";
import gAspectj from "highlight.js/lib/languages/aspectj";
import gAutohotkey from "highlight.js/lib/languages/autohotkey";
import gAutoit from "highlight.js/lib/languages/autoit";
import gAvrasm from "highlight.js/lib/languages/avrasm";
import gAwk from "highlight.js/lib/languages/awk";
import gAxapta from "highlight.js/lib/languages/axapta";
import gBash from "highlight.js/lib/languages/bash";
import gBasic from "highlight.js/lib/languages/basic";
import gBnf from "highlight.js/lib/languages/bnf";
import gBrainfuck from "highlight.js/lib/languages/brainfuck";
import gC from "highlight.js/lib/languages/c";
import gCal from "highlight.js/lib/languages/cal";
import gCapnproto from "highlight.js/lib/languages/capnproto";
import gCeylon from "highlight.js/lib/languages/ceylon";
import gClean from "highlight.js/lib/languages/clean";
import gClojure from "highlight.js/lib/languages/clojure";
import gClojureRepl from "highlight.js/lib/languages/clojure-repl";
import gCmake from "highlight.js/lib/languages/cmake";
import gCoffeescript from "highlight.js/lib/languages/coffeescript";
import gCoq from "highlight.js/lib/languages/coq";
import gCos from "highlight.js/lib/languages/cos";
import gCpp from "highlight.js/lib/languages/cpp";
import gCrmsh from "highlight.js/lib/languages/crmsh";
import gCrystal from "highlight.js/lib/languages/crystal";
import gCsharp from "highlight.js/lib/languages/csharp";
import gCsp from "highlight.js/lib/languages/csp";
import gCss from "highlight.js/lib/languages/css";
import gD from "highlight.js/lib/languages/d";
import gMarkdown from "highlight.js/lib/languages/markdown";
import gDart from "highlight.js/lib/languages/dart";
import gDelphi from "highlight.js/lib/languages/delphi";
import gDiff from "highlight.js/lib/languages/diff";
import gDjango from "highlight.js/lib/languages/django";
import gDns from "highlight.js/lib/languages/dns";
import gDockerfile from "highlight.js/lib/languages/dockerfile";
import gDos from "highlight.js/lib/languages/dos";
import gDsconfig from "highlight.js/lib/languages/dsconfig";
import gDts from "highlight.js/lib/languages/dts";
import gDust from "highlight.js/lib/languages/dust";
import gEbnf from "highlight.js/lib/languages/ebnf";
import gElixir from "highlight.js/lib/languages/elixir";
import gElm from "highlight.js/lib/languages/elm";
import gRuby from "highlight.js/lib/languages/ruby";
import gErb from "highlight.js/lib/languages/erb";
import gErlangRepl from "highlight.js/lib/languages/erlang-repl";
import gErlang from "highlight.js/lib/languages/erlang";
import gExcel from "highlight.js/lib/languages/excel";
import gFix from "highlight.js/lib/languages/fix";
import gFlix from "highlight.js/lib/languages/flix";
import gFortran from "highlight.js/lib/languages/fortran";
import gFsharp from "highlight.js/lib/languages/fsharp";
import gGams from "highlight.js/lib/languages/gams";
import gGauss from "highlight.js/lib/languages/gauss";
import gGcode from "highlight.js/lib/languages/gcode";
import gGherkin from "highlight.js/lib/languages/gherkin";
import gGlsl from "highlight.js/lib/languages/glsl";
import gGml from "highlight.js/lib/languages/gml";
import gGo from "highlight.js/lib/languages/go";
import gGolo from "highlight.js/lib/languages/golo";
import gGradle from "highlight.js/lib/languages/gradle";
import gGraphql from "highlight.js/lib/languages/graphql";
import gGroovy from "highlight.js/lib/languages/groovy";
import gHaml from "highlight.js/lib/languages/haml";
import gHandlebars from "highlight.js/lib/languages/handlebars";
import gHaskell from "highlight.js/lib/languages/haskell";
import gHaxe from "highlight.js/lib/languages/haxe";
import gHsp from "highlight.js/lib/languages/hsp";
import gHttp from "highlight.js/lib/languages/http";
import gHy from "highlight.js/lib/languages/hy";
import gInform7 from "highlight.js/lib/languages/inform7";
import gIni from "highlight.js/lib/languages/ini";
import gIrpf90 from "highlight.js/lib/languages/irpf90";
import gIsbl from "highlight.js/lib/languages/isbl";
import gJava from "highlight.js/lib/languages/java";
import gJavascript from "highlight.js/lib/languages/javascript";
import gJbossCli from "highlight.js/lib/languages/jboss-cli";
import gJson from "highlight.js/lib/languages/json";
import gJulia from "highlight.js/lib/languages/julia";
import gJuliaRepl from "highlight.js/lib/languages/julia-repl";
import gKotlin from "highlight.js/lib/languages/kotlin";
import gLasso from "highlight.js/lib/languages/lasso";
import gLatex from "highlight.js/lib/languages/latex";
import gLdif from "highlight.js/lib/languages/ldif";
import gLeaf from "highlight.js/lib/languages/leaf";
import gLess from "highlight.js/lib/languages/less";
import gLisp from "highlight.js/lib/languages/lisp";
import gLivecodeserver from "highlight.js/lib/languages/livecodeserver";
import gLivescript from "highlight.js/lib/languages/livescript";
import gLlvm from "highlight.js/lib/languages/llvm";
import gLsl from "highlight.js/lib/languages/lsl";
import gLua from "highlight.js/lib/languages/lua";
import gMakefile from "highlight.js/lib/languages/makefile";
import gMathematica from "highlight.js/lib/languages/mathematica";
import gMatlab from "highlight.js/lib/languages/matlab";
import gMaxima from "highlight.js/lib/languages/maxima";
import gMel from "highlight.js/lib/languages/mel";
import gMercury from "highlight.js/lib/languages/mercury";
import gMipsasm from "highlight.js/lib/languages/mipsasm";
import gMizar from "highlight.js/lib/languages/mizar";
import gPerl from "highlight.js/lib/languages/perl";
import gMojolicious from "highlight.js/lib/languages/mojolicious";
import gMonkey from "highlight.js/lib/languages/monkey";
import gMoonscript from "highlight.js/lib/languages/moonscript";
import gN1ql from "highlight.js/lib/languages/n1ql";
import gNestedtext from "highlight.js/lib/languages/nestedtext";
import gNginx from "highlight.js/lib/languages/nginx";
import gNim from "highlight.js/lib/languages/nim";
import gNix from "highlight.js/lib/languages/nix";
import gNodeRepl from "highlight.js/lib/languages/node-repl";
import gNsis from "highlight.js/lib/languages/nsis";
import gObjectivec from "highlight.js/lib/languages/objectivec";
import gOcaml from "highlight.js/lib/languages/ocaml";
import gOpenscad from "highlight.js/lib/languages/openscad";
import gOxygene from "highlight.js/lib/languages/oxygene";
import gParser3 from "highlight.js/lib/languages/parser3";
import gPf from "highlight.js/lib/languages/pf";
import gPgsql from "highlight.js/lib/languages/pgsql";
import gPhp from "highlight.js/lib/languages/php";
import gPhpTemplate from "highlight.js/lib/languages/php-template";
import gPlaintext from "highlight.js/lib/languages/plaintext";
import gPony from "highlight.js/lib/languages/pony";
import gPowershell from "highlight.js/lib/languages/powershell";
import gProcessing from "highlight.js/lib/languages/processing";
import gProfile from "highlight.js/lib/languages/profile";
import gProlog from "highlight.js/lib/languages/prolog";
import gProperties from "highlight.js/lib/languages/properties";
import gProtobuf from "highlight.js/lib/languages/protobuf";
import gPuppet from "highlight.js/lib/languages/puppet";
import gPurebasic from "highlight.js/lib/languages/purebasic";
import gPython from "highlight.js/lib/languages/python";
import gPythonRepl from "highlight.js/lib/languages/python-repl";
import gQ from "highlight.js/lib/languages/q";
import gQml from "highlight.js/lib/languages/qml";
import gR from "highlight.js/lib/languages/r";
import gReasonml from "highlight.js/lib/languages/reasonml";
import gRib from "highlight.js/lib/languages/rib";
import gRoboconf from "highlight.js/lib/languages/roboconf";
import gRouteros from "highlight.js/lib/languages/routeros";
import gRsl from "highlight.js/lib/languages/rsl";
import gRuleslanguage from "highlight.js/lib/languages/ruleslanguage";
import gRust from "highlight.js/lib/languages/rust";
import gSas from "highlight.js/lib/languages/sas";
import gScala from "highlight.js/lib/languages/scala";
import gScheme from "highlight.js/lib/languages/scheme";
import gScilab from "highlight.js/lib/languages/scilab";
import gScss from "highlight.js/lib/languages/scss";
import gShell from "highlight.js/lib/languages/shell";
import gSmali from "highlight.js/lib/languages/smali";
import gSmalltalk from "highlight.js/lib/languages/smalltalk";
import gSml from "highlight.js/lib/languages/sml";
import gSqf from "highlight.js/lib/languages/sqf";
import gSql from "highlight.js/lib/languages/sql";
import gStan from "highlight.js/lib/languages/stan";
import gStata from "highlight.js/lib/languages/stata";
import gStep21 from "highlight.js/lib/languages/step21";
import gStylus from "highlight.js/lib/languages/stylus";
import gSubunit from "highlight.js/lib/languages/subunit";
import gSwift from "highlight.js/lib/languages/swift";
import gTaggerscript from "highlight.js/lib/languages/taggerscript";
import gYaml from "highlight.js/lib/languages/yaml";
import gTap from "highlight.js/lib/languages/tap";
import gTcl from "highlight.js/lib/languages/tcl";
import gThrift from "highlight.js/lib/languages/thrift";
import gTp from "highlight.js/lib/languages/tp";
import gTwig from "highlight.js/lib/languages/twig";
import gTypescript from "highlight.js/lib/languages/typescript";
import gVala from "highlight.js/lib/languages/vala";
import gVbnet from "highlight.js/lib/languages/vbnet";
import gVbscript from "highlight.js/lib/languages/vbscript";
import gVbscriptHtml from "highlight.js/lib/languages/vbscript-html";
import gVerilog from "highlight.js/lib/languages/verilog";
import gVhdl from "highlight.js/lib/languages/vhdl";
import gVim from "highlight.js/lib/languages/vim";
import gWasm from "highlight.js/lib/languages/wasm";
import gWren from "highlight.js/lib/languages/wren";
import gX86asm from "highlight.js/lib/languages/x86asm";
import gXl from "highlight.js/lib/languages/xl";
import gXquery from "highlight.js/lib/languages/xquery";
import gZephir from "highlight.js/lib/languages/zephir";

hljs.registerLanguage("1c", g1c);
hljs.registerLanguage("abnf", gAbnf);
hljs.registerLanguage("accesslog", gAccesslog);
hljs.registerLanguage("actionscript", gActionscript);
hljs.registerLanguage("ada", gAda);
hljs.registerLanguage("angelscript", gAngelscript);
hljs.registerLanguage("apache", gApache);
hljs.registerLanguage("applescript", gApplescript);
hljs.registerLanguage("arcade", gArcade);
hljs.registerLanguage("arduino", gArduino);
hljs.registerLanguage("armasm", gArmasm);
hljs.registerLanguage("xml", gXml);
hljs.registerLanguage("asciidoc", gAsciidoc);
hljs.registerLanguage("aspectj", gAspectj);
hljs.registerLanguage("autohotkey", gAutohotkey);
hljs.registerLanguage("autoit", gAutoit);
hljs.registerLanguage("avrasm", gAvrasm);
hljs.registerLanguage("awk", gAwk);
hljs.registerLanguage("axapta", gAxapta);
hljs.registerLanguage("bash", gBash);
hljs.registerLanguage("basic", gBasic);
hljs.registerLanguage("bnf", gBnf);
hljs.registerLanguage("brainfuck", gBrainfuck);
hljs.registerLanguage("c", gC);
hljs.registerLanguage("cal", gCal);
hljs.registerLanguage("capnproto", gCapnproto);
hljs.registerLanguage("ceylon", gCeylon);
hljs.registerLanguage("clean", gClean);
hljs.registerLanguage("clojure", gClojure);
hljs.registerLanguage("clojure-repl", gClojureRepl);
hljs.registerLanguage("cmake", gCmake);
hljs.registerLanguage("coffeescript", gCoffeescript);
hljs.registerLanguage("coq", gCoq);
hljs.registerLanguage("cos", gCos);
hljs.registerLanguage("cpp", gCpp);
hljs.registerLanguage("crmsh", gCrmsh);
hljs.registerLanguage("crystal", gCrystal);
hljs.registerLanguage("csharp", gCsharp);
hljs.registerLanguage("csp", gCsp);
hljs.registerLanguage("css", gCss);
hljs.registerLanguage("d", gD);
hljs.registerLanguage("markdown", gMarkdown);
hljs.registerLanguage("dart", gDart);
hljs.registerLanguage("delphi", gDelphi);
hljs.registerLanguage("diff", gDiff);
hljs.registerLanguage("django", gDjango);
hljs.registerLanguage("dns", gDns);
hljs.registerLanguage("dockerfile", gDockerfile);
hljs.registerLanguage("dos", gDos);
hljs.registerLanguage("dsconfig", gDsconfig);
hljs.registerLanguage("dts", gDts);
hljs.registerLanguage("dust", gDust);
hljs.registerLanguage("ebnf", gEbnf);
hljs.registerLanguage("elixir", gElixir);
hljs.registerLanguage("elm", gElm);
hljs.registerLanguage("ruby", gRuby);
hljs.registerLanguage("erb", gErb);
hljs.registerLanguage("erlang-repl", gErlangRepl);
hljs.registerLanguage("erlang", gErlang);
hljs.registerLanguage("excel", gExcel);
hljs.registerLanguage("fix", gFix);
hljs.registerLanguage("flix", gFlix);
hljs.registerLanguage("fortran", gFortran);
hljs.registerLanguage("fsharp", gFsharp);
hljs.registerLanguage("gams", gGams);
hljs.registerLanguage("gauss", gGauss);
hljs.registerLanguage("gcode", gGcode);
hljs.registerLanguage("gherkin", gGherkin);
hljs.registerLanguage("glsl", gGlsl);
hljs.registerLanguage("gml", gGml);
hljs.registerLanguage("go", gGo);
hljs.registerLanguage("golo", gGolo);
hljs.registerLanguage("gradle", gGradle);
hljs.registerLanguage("graphql", gGraphql);
hljs.registerLanguage("groovy", gGroovy);
hljs.registerLanguage("haml", gHaml);
hljs.registerLanguage("handlebars", gHandlebars);
hljs.registerLanguage("haskell", gHaskell);
hljs.registerLanguage("haxe", gHaxe);
hljs.registerLanguage("hsp", gHsp);
hljs.registerLanguage("http", gHttp);
hljs.registerLanguage("hy", gHy);
hljs.registerLanguage("inform7", gInform7);
hljs.registerLanguage("ini", gIni);
hljs.registerLanguage("irpf90", gIrpf90);
hljs.registerLanguage("isbl", gIsbl);
hljs.registerLanguage("java", gJava);
hljs.registerLanguage("javascript", gJavascript);
hljs.registerLanguage("jboss-cli", gJbossCli);
hljs.registerLanguage("json", gJson);
hljs.registerLanguage("julia", gJulia);
hljs.registerLanguage("julia-repl", gJuliaRepl);
hljs.registerLanguage("kotlin", gKotlin);
hljs.registerLanguage("lasso", gLasso);
hljs.registerLanguage("latex", gLatex);
hljs.registerLanguage("ldif", gLdif);
hljs.registerLanguage("leaf", gLeaf);
hljs.registerLanguage("less", gLess);
hljs.registerLanguage("lisp", gLisp);
hljs.registerLanguage("livecodeserver", gLivecodeserver);
hljs.registerLanguage("livescript", gLivescript);
hljs.registerLanguage("llvm", gLlvm);
hljs.registerLanguage("lsl", gLsl);
hljs.registerLanguage("lua", gLua);
hljs.registerLanguage("makefile", gMakefile);
hljs.registerLanguage("mathematica", gMathematica);
hljs.registerLanguage("matlab", gMatlab);
hljs.registerLanguage("maxima", gMaxima);
hljs.registerLanguage("mel", gMel);
hljs.registerLanguage("mercury", gMercury);
hljs.registerLanguage("mipsasm", gMipsasm);
hljs.registerLanguage("mizar", gMizar);
hljs.registerLanguage("perl", gPerl);
hljs.registerLanguage("mojolicious", gMojolicious);
hljs.registerLanguage("monkey", gMonkey);
hljs.registerLanguage("moonscript", gMoonscript);
hljs.registerLanguage("n1ql", gN1ql);
hljs.registerLanguage("nestedtext", gNestedtext);
hljs.registerLanguage("nginx", gNginx);
hljs.registerLanguage("nim", gNim);
hljs.registerLanguage("nix", gNix);
hljs.registerLanguage("node-repl", gNodeRepl);
hljs.registerLanguage("nsis", gNsis);
hljs.registerLanguage("objectivec", gObjectivec);
hljs.registerLanguage("ocaml", gOcaml);
hljs.registerLanguage("openscad", gOpenscad);
hljs.registerLanguage("oxygene", gOxygene);
hljs.registerLanguage("parser3", gParser3);
hljs.registerLanguage("pf", gPf);
hljs.registerLanguage("pgsql", gPgsql);
hljs.registerLanguage("php", gPhp);
hljs.registerLanguage("php-template", gPhpTemplate);
hljs.registerLanguage("plaintext", gPlaintext);
hljs.registerLanguage("pony", gPony);
hljs.registerLanguage("powershell", gPowershell);
hljs.registerLanguage("processing", gProcessing);
hljs.registerLanguage("profile", gProfile);
hljs.registerLanguage("prolog", gProlog);
hljs.registerLanguage("properties", gProperties);
hljs.registerLanguage("protobuf", gProtobuf);
hljs.registerLanguage("puppet", gPuppet);
hljs.registerLanguage("purebasic", gPurebasic);
hljs.registerLanguage("python", gPython);
hljs.registerLanguage("python-repl", gPythonRepl);
hljs.registerLanguage("q", gQ);
hljs.registerLanguage("qml", gQml);
hljs.registerLanguage("r", gR);
hljs.registerLanguage("reasonml", gReasonml);
hljs.registerLanguage("rib", gRib);
hljs.registerLanguage("roboconf", gRoboconf);
hljs.registerLanguage("routeros", gRouteros);
hljs.registerLanguage("rsl", gRsl);
hljs.registerLanguage("ruleslanguage", gRuleslanguage);
hljs.registerLanguage("rust", gRust);
hljs.registerLanguage("sas", gSas);
hljs.registerLanguage("scala", gScala);
hljs.registerLanguage("scheme", gScheme);
hljs.registerLanguage("scilab", gScilab);
hljs.registerLanguage("scss", gScss);
hljs.registerLanguage("shell", gShell);
hljs.registerLanguage("smali", gSmali);
hljs.registerLanguage("smalltalk", gSmalltalk);
hljs.registerLanguage("sml", gSml);
hljs.registerLanguage("sqf", gSqf);
hljs.registerLanguage("sql", gSql);
hljs.registerLanguage("stan", gStan);
hljs.registerLanguage("stata", gStata);
hljs.registerLanguage("step21", gStep21);
hljs.registerLanguage("stylus", gStylus);
hljs.registerLanguage("subunit", gSubunit);
hljs.registerLanguage("swift", gSwift);
hljs.registerLanguage("taggerscript", gTaggerscript);
hljs.registerLanguage("yaml", gYaml);
hljs.registerLanguage("tap", gTap);
hljs.registerLanguage("tcl", gTcl);
hljs.registerLanguage("thrift", gThrift);
hljs.registerLanguage("tp", gTp);
hljs.registerLanguage("twig", gTwig);
hljs.registerLanguage("typescript", gTypescript);
hljs.registerLanguage("vala", gVala);
hljs.registerLanguage("vbnet", gVbnet);
hljs.registerLanguage("vbscript", gVbscript);
hljs.registerLanguage("vbscript-html", gVbscriptHtml);
hljs.registerLanguage("verilog", gVerilog);
hljs.registerLanguage("vhdl", gVhdl);
hljs.registerLanguage("vim", gVim);
hljs.registerLanguage("wasm", gWasm);
hljs.registerLanguage("wren", gWren);
hljs.registerLanguage("x86asm", gX86asm);
hljs.registerLanguage("xl", gXl);
hljs.registerLanguage("xquery", gXquery);
hljs.registerLanguage("zephir", gZephir);

export default hljs;
