apiVersion: apps/v1
kind: Deployment
metadata:
  name: arenasql-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arenasql-cluster
  template:
    metadata:
      labels:
        app: arenasql-cluster
    spec:
      volumes:
        - name: arenasql-volume
          persistentVolumeClaim:
            claimName: arenasql-pvc
      containers:
        - name: arenasql-cluster
          image: arenasql-cluster
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/data
              name: arenasql-volume
          ports:
            - containerPort: 6000
          env:
            - name: RUST_LOG
              value: trace
