[package]
name = "faiss"
version = "0.1.0"
edition = "2021"

[features]
default = ["static"]
static = []


[dependencies]
rand = "0.8.5"
libc = "0.2.151"
strum_macros = "0.25"
getset = "0.1.2"

[build-dependencies]
bindgen = "0.69.1"
cmake = "0.1.50"
