apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - deployment.yaml
configMapGenerator:
  - name: envoy-config
    files:
      - envoy.yaml
commonLabels:
  app: envoy
  version: "1.0"
