[package]
name = "cloud"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
deno_core.workspace = true
serde.workspace = true
serde_json.workspace = true
jsonwebtoken.workspace = true
common = { path = "../common", features = ["data_query"]}
jsruntime = { path = "../jsruntime" }