[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
derivative.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
indexmap.workspace = true
url.workspace = true
tokio.workspace = true
tracing.workspace = true

digest.workspace = true
hex.workspace = true
md4.workspace = true
md-5.workspace = true
sha-1.workspace = true
sha2.workspace = true
ripemd.workspace = true

deno_core.workspace = true
deno_fetch.workspace = true
deno_web.workspace = true
