[package]
name = "common"
version = "0.1.0"
edition = "2021"

[features]
fs-rerun-if-changed=[]

[dependencies]
anyhow.workspace = true
derivative.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
indexmap.workspace = true
url.workspace = true
tokio.workspace = true
http.workspace = true
hyper.workspace = true
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
futures.workspace = true
bytes.workspace = true
postgres.workspace = true
tokio-postgres.workspace = true
tokio-rustls.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true
webpki-roots.workspace = true
rustls-native-certs.workspace = true
heck.workspace = true
uuid.workspace = true
ring.workspace = true
chrono.workspace = true
pathdiff.workspace = true
once_cell.workspace = true

digest.workspace = true
hex.workspace = true
md4.workspace = true
md-5.workspace = true
sha-1.workspace = true
sha2.workspace = true
ripemd.workspace = true
rand.workspace = true

swc_common.workspace = true
swc_ecma_visit.workspace = true
swc_ecma_ast.workspace = true

deno_core.workspace = true
deno_fetch.workspace = true
deno_web.workspace = true
deno_ast.workspace = true
