apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: dagger
          imagePullPolicy: Always
          args:
            - "/bin/dagger"
            - "server"
            - "serve"
            - "--port"
            - "9000"
            - "--enable-cloud-ext"
            - "--s3bucket"
            - "portal-prod-2024"
            - "apps/portal-website/2024-05-02-16-37/server/index.mjs"
          ports:
            - containerPort: 9000
          envFrom:
            - secretRef:
                name: website-env-secrets
