apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: tilt-arena-
bases:
  - ./postgres
commonLabels:
  group: core-services
resources:
  - pvc.yaml
secretGenerator:
  - name: postgres-secrets
    envs:
      - secrets/postgres.env
images:
  - name: postgres
    newName: postgres
    newTag: "15"
