apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: tilt-arena-
commonLabels:
  group: core-services
resources:
  - ./postgres
  - ./minio
  # - ../prod/arenasql-cluster
  # - app-cluster-config.yaml
  - arenasql-pvc.yaml
  - postgres-pvc.yaml
  - minio-pvc.yaml
secretGenerator:
  - name: postgres-secrets
    envs:
      - secrets/postgres.env
images:
  - name: postgres
    newName: postgres
    newTag: "15"
  - name: minio
    newName: quay.io/minio/minio
    newTag: latest
  - name: envoy
    newName: envoyproxy/envoy
    newTag: v1.29-latest
