apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - deployment.yaml
commonLabels:
  app: app-cluster
  version: "1.0"
secretGenerator:
  - name: app-cluster-env-secrets
    envs:
      - secrets/app-cluster.env
images:
  - name: app-cluster
    newName: app-cluster
