[workspace]

members = [
  "jsruntime",
  "dagger"
]
resolver = "2"

[workspace.dependencies]
serde_json = { version = "1.0.85", features = ["std", "preserve_order"] }
tokio = { version = "1.21.1", features = ["full"] }
futures = "0.3.25"
reqwest = { version = "0.11", features = ["json", "rustls-tls", "stream", "gzip", "brotli", "socks"] }
anyhow = "1.0.68"
ring = "0.16.20"
flate2 = "1.0.24"
tar = "0.4.38"
base64 = "0.20.0"
log = "0.4"
env_logger = "0.10.0"
indexmap = { version = "1.9.2", features = ["serde-1"] }
derivative = "2.2.0"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.0.29", features = ["derive"] }
url = "2.3.1"
criterion = "0.4.0"
once_cell = "1.16.0"
chrono = "0.4.23"
smallvec = "1.10.0"
serde_yaml = "0.9"

deno_core = "0.169.0"
deno_console = "0.87.0"
deno_url = "0.87.0"
deno_fetch = "0.111.0"
deno_web = "0.118.0"
deno_webidl = "0.87.0"

swc_common = "0.29.28"
swc_ecma_parser = "0.124.4"
swc_ecma_ast = "0.96.2"
swc_ecma_transforms_typescript = "0.164.5"
swc_ecma_visit = "0.82.2"
swc_ecma_codegen = "0.129.7"

[profile.release]
codegen-units = 1
incremental = true
lto = true
