[workspace]

members = [
  "jsruntime",
  "server",
  "workspace",
  "dagger"
]
resolver = "2"

[workspace.dependencies]
serde_json = { version = "1.0.85", features = ["std", "preserve_order"] }
tokio = { version = "1.21.1", features = ["full"] }
futures = "0.3.25"
reqwest = { version = "0.11", features = ["json", "rustls-tls", "stream", "gzip", "brotli", "socks"] }
anyhow = "1.0.68"
ring = "0.16.20"
flate2 = "1.0.24"
tar = "0.4.38"
base64 = "0.20.0"
log = "0.4"
env_logger = "0.10.0"
indexmap = { version = "1.9.2", features = ["serde-1"] }
derivative = "2.2.0"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.0.29", features = ["derive"] }
url = "2.3.1"
criterion = "0.4.0"
once_cell = "1.16.0"
chrono = "0.4.23"
smallvec = "1.10.0"
serde_yaml = "0.9"
hyper = "0.14.24"
axum = "0.6.4"
bytes = "=1.2.1"
http = "0.2.8"
tower = { version = "0.4.13" }
tower-http = { version = "0.3.5", features = ["full"] }

deno_core = "0.171.0"
deno_console = "0.89.0"
deno_url = "0.89.0"
deno_fetch = "0.113.0"
deno_web = "0.120.0"
deno_webidl = "0.89.0"
deno_crypto = "0.103.0"
deno_ast = { version = "0.24.0", features = ["transpiling"] }

# swc's version bumping is very buggy, so we pin all swc versions to prevent
swc_common = "=0.29.29"
swc_ecma_parser = "=0.124.5"
swc_ecma_ast = "=0.96.3"
swc_ecma_transforms_typescript = "=0.164.10"
swc_ecma_visit = "=0.82.3"
swc_ecma_codegen = "=0.129.8"

[profile.release]
strip = true
debug = 1
codegen-units = 1
incremental = true
lto = true

[profile.dev.package.jsruntime]
opt-level = 3
