apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
    - name: api
      port: 8001
      targetPort: 8001
    - name: console
      port: 10001
      targetPort: 10001
